# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-13"
  config.vm.hostname = "debian-base"
  config.vm.network "private_network", ip: "192.168.56.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "debian-base"
    vb.memory = 1024
    vb.cpus = 1
    vb.gui = false  
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "VM TP – Debian Base" > /etc/motd
  SHELL


  #config.ssh.timeout = 60
  #config.ssh.shell = "bash -lc"
end